### ISSUE TITLE
Analyze and determine web technology stack for project

### ISSUE THREAD

**Issue by mckoon** [healthbam/healthbam#10]

**Comment by RyanBard** [comment]
Handled in issue #1: https://github.com/healthbam/healthbam/issues/1
In PR #16: https://github.com/healthbam/healthbam/pull/16

**Comment by RyanBard** [comment]
I have chosen:

AngularJS 1.x - It is stable, popular, and 3 of our devs are familiar with it.
Spring Boot - It is popular, relatively easy to get setup, very cloud compatible, and it should be easy for all of our devs to work with it.
Heroku - It is popular, has many tutorials and good documentation, and has a good free tier.
