### ISSUE TITLE
Check for programs before allowing an organization to be deleted

### ISSUE THREAD

**Issue by jlgettings** [healthbam/healthbam#225]

**Comment by mckoon** [comment]
My recommendation for how to do this is to run a MapQuery for the organization. This will return the URL for the map of all the organization's programs, as well as an array of all the programs.

If the programs array is empty, then delete is allowed. This call also lets you show the organization map and list basic program info for all the programs (if we want to).

**Comment by mckoon** [comment]
The work I described above is #170, which is the REST call that should be used for this check.
