### ISSUE TITLE
Sign Out menu obscures logout button.

### ISSUE THREAD

**Issue by kpsfoo** [healthbam/healthbam#243]
The Sign Out menu shouldn't obscure the logout button as it can lead to accidental clicks. It should appear directly below the sign out button.

**Comment by mckoon** [comment]
Disagree. https://material.google.com/components/menus.html#menus-behavior

**Comment by mckoon** [comment]
From that link 

> Menus are positioned over their emitting elements such that the currently selected menu item appears on top of the emitting element.

**Comment by kpsfoo** [comment]
Jay and I discussed this via PM on Slack. Low priority for now but needs fixing.

**Comment by mckoon** [comment]
There is a second menu item now.  Closing as invalid.
