### ISSUE TITLE
Which UI Framework?

### ISSUE THREAD

**Issue by mckoon** [healthbam/healthbam#35]
We need to determine the UI framework to pursue.

As we are using AngularJS for the front-end, there are two frameworks that are easy to use which which I have experience: Material Design, via Angular Material, or Twitter Bootstrap via Angular ui-bootstrap.

We know that the customer wants the UI to be responsive so that it can be viewed on different types of devices. I am leaning towards Material Design, but we need to make a decision.

Material Design: https://material.google.com/
Angular Material: https://material.angularjs.org/

Twitter Bootstrap: http://getbootstrap.com/
Angular UI Bootstrap: https://angular-ui.github.io/bootstrap/

**Comment by RyanBard** [comment]
My preference would be Angular Material until proven otherwise.  In theory, it'll be easier to work with mobile devices with that (it seems to have responsive design in mind more so than angular-ui-bootstrap).

**Comment by mckoon** [comment]
Going with Angular Material
