### ISSUE TITLE
Add a console.log("KP was here") to the app

### ISSUE THREAD

**Issue by RyanBard** [healthbam/healthbam#71]
In our before class meeting, let's get a change into "production".

Prepare by finishing #75.

Then look for the kp function in main.component.js.  This has a log call printing "TODO" in the console (open the developer tools of your browser and you should see messages in the console).

Change the TODO to different message, push that change to your github fork, create a Pull Request (PR), and merge that change to be able to see it changed in production.

We can go through some of this process together.  In #75, prepare to have the software necessary to build installed so we can finish in a short amount of time (possibly before class on wednesday).

**Comment by kpsfoo** [comment]
I don't understand this.

**Comment by RyanBard** [comment]
I'm going to go ahead and close #75 and #71 out.  @kpsfoo isn't tasked with code changes and won't need to setup/rampup on these things.
